[package]
name = "rust-action"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri-cli = "=1.2.2"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
