name: Build and deploy
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - run: mv target/release/rust-action bin/rust-action-${{ matrix.platform }}

      - name: GIT commit and push all changed files
        env:
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git pull
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add bin
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
