name: Build and deploy
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/build.yml"
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - run: mv target/release/rust-action bin/rust-action-${{ matrix.platform }}
        if: matrix.platform == 'ubuntu-latest'

      - run: mv target/release/rust-action bin/rust-action-${{ matrix.platform }}
        if: matrix.platform == 'macos-latest'

      - run: move /y "target\release\rust-action.exe" "bin\rust-action-${{ matrix.platform }}.exe"
        if: matrix.platform == 'windows-latest'

      - name: GIT commit and push all changed files
        env:
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git pull
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add bin
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
