name: Test action
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Build and deploy
    types:
      - completed

jobs:
  audit:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: Run rust-action
        uses: simonhyll/rust-action@main
