name: Test action
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Build and deploy
    types:
      - completed

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run cargo audit fix
        uses: simonhyll/rust-action@v1
